### ISSUE TITLE
failed to lead

### ISSUE THREAD

**Issue by forbest** [Manliketjb/qb-documents#2]
[ script:qb-documents] Error loading script server.lua in resource qb-documents: @qb-documents/server.lua:4: attempt to index a nil value (global 'QBCore')
[ script:qb-documents] stack traceback:
[ script:qb-documents] 	@qb-documents/server.lua:4: in main chunk
[    c-scripting-core] Failed to load script server.lua.

**Comment by Manliketjb** [comment]
> [ script:qb-documents] Error loading script server.lua in resource qb-documents: @qb-documents/server.lua:4: attempt to index a nil value (global 'QBCore') [ script:qb-documents] stack traceback: [ script:qb-documents] @qb-documents/server.lua:4: in main chunk [ c-scripting-core] Failed to load script server.lua.

script only works with the updated QBCore

**Comment by forbest** [comment]
fixed I added 
TriggerEvent('QBcore:GetObject', function(obj) QBcore = obj end)
to line 2 of server.lua
